
O="/afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits" # the base output directory



## fakes application
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits_FRappl --sP SR_.*._.* -p _standard_prompt_.* -p _standard_fakes_.* -p _large_sig_TChiNeu_WZ_.* -p _large_sig_TChiNeu_SlepSneu_.*
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits_FRappl --sP SR_a_a --sP SR_b_a -p _standard_prompt_.* -p _standard_fakes_.* -p _larger_sig_TChiNeu_WZ_.* -p _larger_sig_TChiNeu_SlepSneu_.*
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits_FRappl --sP SR_c_b --sP SR_c_c -p _standard_prompt_.* -p _standard_fakes_.* -p _sig_TChiNeu_WZ_.* -p _sig_TChiNeu_SlepSneu_.*

## fakes gen matched
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits --sP SR_.*._.* -p _standard_prompt_.* -p _matched_fakes_.* -p _large_sig_TChiNeu_WZ_.* -p _large_sig_TChiNeu_SlepSneu_.*
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits --sP SR_a_a --sP SR_b_a -p _standard_prompt_.* -p _matched_fakes_.* -p _larger_sig_TChiNeu_WZ_.* -p _larger_sig_TChiNeu_SlepSneu_.*
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits --sP SR_c_b --sP SR_c_c -p _standard_prompt_.* -p _matched_fakes_.* -p _sig_TChiNeu_WZ_.* -p _sig_TChiNeu_SlepSneu_.*

## WZ control region
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --scaleBkgToData --showSF -W 'vtxWeight_Loop' --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-15_ewk8tev_upperlimits_WZ -p data -p _unscaled_WZ --sP met --sP mtW








## other stuff ------------------------------------------

## RA5 plots
#python mcPlots.py -P /data1/p/peruzzi/skimmed_mix_nov22 --neg --s2v --tree treeProducerSusyMultilepton  -F sf/t {P}/5_allnewfriends_v7/evVarFriend_{cname}.root --mcc susy-multilepton/susy_2lssinc_triggerdefs.txt susy-multilepton/mca-Spring15-analysis-all.txt susy-multilepton/susy_2lss_multiiso.txt -f -j 8 --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 susy-multilepton/susy_2lss_coarse_selplots.txt --showMCError  --FMC sf/t {P}/1_purew_mix_true_nvtx/evVarFriend_{cname}.root -W 'vtxWeight*btagMediumSF_Mini*triggerSF_Loop*leptonSF_Loop' -l 2.160000 -p data -p _fakesappl_data -p _promptratesub -p _flipsappl_data -p _standard_prompt_.* -p _sig_.* --showIndivSigs --noStackSig --plotgroup _fakesappl_data+=_promptratesub --plotgroup _fakesappl_data_ewk_Up+=_promptratesub_ewk_Up --plotgroup _fakesappl_data_ewk_Dn+=_promptratesub_ewk_Dn -X lep1_pt25 -X lep2_pt25 -A alwaystrue SR_ii 'SR>0' --wide --sP SR_ii --sP SR_ii_log --sP SR_ii_regrouped  --pdir /afs/cern.ch/user/p/peruzzi/www/test_ra5plots_dec03/dataPrediction_nosig_SR_ii —plotmode norm

## validation plots
#python mcPlots.py susy-multilepton/signal_validation/mca_ewkino.txt susy-multilepton/signal_validation/cuts_ewkino.txt susy-multilepton/signal_validation/plots_ewkino.txt -P /shome/cheidegg/o/2016-03-12_ewksignals/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-03-16_signal_validation --plotmode norm
#python mcPlots.py susy-multilepton/signal_validation/mca_ewkino.txt susy-multilepton/signal_validation/cuts_ewkino.txt susy-multilepton/signal_validation/plots_ewkino.txt -P /shome/cheidegg/o/2016-03-12_ewksignals/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 --sP nJet40 --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-03-16_signal_validation --plotmode norm -p _sig_TChiNeu_SlepSneu_450_300

## ewk stuff
##python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root -l 10.0 -p _standard_prompt_ttW --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-12_ewk8tev_upperlimits --wide --sP SR_a

#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' -p _standard_prompt_.* -p _standard_fakes_.*  --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-12_ewk8tev_upperlimits --wide --sP SR --sP SR_a --sP SR_b --sP SR_c -p _sig_TChiNeu_WZ_.* _sig_TChiNeu_SlepSneu_.*
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /mnt/t3nfs01/data01/shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop' -p _standard_prompt_.* -p _standard_fakes_.*  --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-04-12_ewk8tev_upperlimits --wide --sP SR
#--sP SR --sP SR_a --sP SR_b --sP SR_c
#python mcPlots.py susy-multilepton/ewk_upperlimits/mca_ewkino.txt susy-multilepton/ewk_upperlimits/cuts_ewkino.txt susy-multilepton/ewk_upperlimits/plots_ewkino.txt -P /shome/cheidegg/o/2016-03-18_ewktrees/ --neg --s2v --tree treeProducerSusyMultilepton -f -j 8 --lspam '#bf{CMS} #it{Simulation}' --legendWidth 0.20 --legendFontSize 0.035 --showRatio --maxRatioRange 0 3 -F sf/t {P}/leptonJetReCleanerSusyRA7/evVarFriend_{cname}.root -F sf/t {P}/leptonChoiceEWK/evVarFriend_{cname}.root --mcc susy-multilepton/ewk_upperlimits/mcc_susy_2lssinc_triggerdefs.txt --showMCError -l 10.0 --showIndivSigs --noStackSig -W 'vtxWeight_Loop*btagMediumSF_Mini*leptonSF_Loop' -p _standard_prompt_.* -p _sig_.*  -p _fakesappl_data --pdir /afs/cern.ch/user/c/cheidegg/www/heppy/2016-03-20_ewk8tev_upperlimits --wide --sP SR --sP SR_a --sP SR_b --sP SR_c



